---
- hosts: "{{ hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install Apache httpd
      yum:
        name: httpd
        state: present
    - name: Start and enable Apache httpd
      service:
        name: httpd
        state: started
        enabled: yes